// Generated by Tools/generate_fallback_script_catalog_swift.py. Do not edit.
// Semantic source: openspec/changes/add-c1-demo-capability-governance/ownership-map.yaml
// T0 registry SHA-256: e42c288796ac1e40763854486c96658cf7f76bc585f3f0cfd84f773e1c59e160

public enum RuntimePresentationSafeReasonKind: String, CaseIterable, Codable, Hashable, Sendable {
    case safetyPolicy = "safety_policy"
    case clarificationRequired = "clarification_required"
    case capabilityNotMounted = "capability_not_mounted"
    case notAvailableInDemo = "not_available_in_demo"
    case runtimeUnavailable = "runtime_unavailable"
    case alreadyDone = "already_done"

    public init?(finiteReason: String) {
        guard let projection = RuntimePresentationReasonAuthority.projection(forFiniteReason: finiteReason) else {
            return nil
        }
        self = projection.safeReasonKind
    }
}

public struct RuntimePresentationReasonProjection: Equatable, Sendable {
    public let safeReasonKind: RuntimePresentationSafeReasonKind
    public let result: DemoRuntimeResult
}

public enum RuntimePresentationReasonAuthority {
    public static let finiteReasons: [String] = [
        "safety_or_policy_refusal",
        "clarify_missing_slot",
        "unmounted_tool_name",
        "name_rejected",
        "fast_path_no_match",
        "unsupported_tool_plan",
        "no_representative_tool",
        "runtime_execution_error",
        "already_state_noop",
    ]

    private static let projections: [String: RuntimePresentationReasonProjection] = [
        "safety_or_policy_refusal": RuntimePresentationReasonProjection(
            safeReasonKind: .safetyPolicy,
            result: .refusalSafetyOrPolicy
        ),
        "clarify_missing_slot": RuntimePresentationReasonProjection(
            safeReasonKind: .clarificationRequired,
            result: .clarifyMissingSlot
        ),
        "unmounted_tool_name": RuntimePresentationReasonProjection(
            safeReasonKind: .capabilityNotMounted,
            result: .refusalNoAvailableTool
        ),
        "name_rejected": RuntimePresentationReasonProjection(
            safeReasonKind: .capabilityNotMounted,
            result: .refusalNoAvailableTool
        ),
        "fast_path_no_match": RuntimePresentationReasonProjection(
            safeReasonKind: .notAvailableInDemo,
            result: .refusalNoAvailableTool
        ),
        "unsupported_tool_plan": RuntimePresentationReasonProjection(
            safeReasonKind: .notAvailableInDemo,
            result: .refusalNoAvailableTool
        ),
        "no_representative_tool": RuntimePresentationReasonProjection(
            safeReasonKind: .notAvailableInDemo,
            result: .refusalNoAvailableTool
        ),
        "runtime_execution_error": RuntimePresentationReasonProjection(
            safeReasonKind: .runtimeUnavailable,
            result: .runtimeError
        ),
        "already_state_noop": RuntimePresentationReasonProjection(
            safeReasonKind: .alreadyDone,
            result: .alreadyStateNoop
        ),
    ]

    public static func projection(forFiniteReason finiteReason: String) -> RuntimePresentationReasonProjection? {
        projections[finiteReason]
    }
}
