// Generated by Tools/generate_fallback_script_catalog_swift.py. Do not edit.
// Semantic source: openspec/changes/add-c1-demo-capability-governance/ownership-map.yaml
// T0 registry SHA-256: c19bc9b9d107de0fdcc6e56b4ff1995a072961d4d9fa75105e983b2ec48d7ce3

public enum RuntimeFiniteReason: String, CaseIterable, Codable, Hashable, Sendable {
    case safetyOrPolicyRefusal = "safety_or_policy_refusal"
    case clarifyMissingSlot = "clarify_missing_slot"
    case unmountedToolName = "unmounted_tool_name"
    case nameRejected = "name_rejected"
    case fastPathNoMatch = "fast_path_no_match"
    case unsupportedToolPlan = "unsupported_tool_plan"
    case noRepresentativeTool = "no_representative_tool"
    case runtimeExecutionError = "runtime_execution_error"
    case staleStateRevision = "stale_state_revision"
    case alreadyStateNoop = "already_state_noop"
    case lexicalInvalid = "lexical_invalid"
    case numericOverflow = "numeric_overflow"
    case arithmeticOverflow = "arithmetic_overflow"
    case unsupportedPrecision = "unsupported_precision"
    case outOfRange = "out_of_range"
    case malformedCurrent = "malformed_current"
    case unsupportedUnitReference = "unsupported_unit_reference"
    case contractViolation = "contract_violation"
    case stateQuery = "state_query"
    case capabilityQuery = "capability_query"
    case cancelTooLate = "cancel_too_late"
}

public enum RuntimePresentationSafeReasonKind: String, CaseIterable, Codable, Hashable, Sendable {
    case safetyPolicy = "safety_policy"
    case clarificationRequired = "clarification_required"
    case capabilityNotMounted = "capability_not_mounted"
    case notAvailableInDemo = "not_available_in_demo"
    case runtimeUnavailable = "runtime_unavailable"
    case alreadyDone = "already_done"
    case lexicalInvalid = "lexical_invalid"
    case numericOverflow = "numeric_overflow"
    case unsupportedPrecision = "unsupported_precision"
    case outOfRange = "out_of_range"
    case malformedCurrent = "malformed_current"
    case unsupportedUnitReference = "unsupported_unit_reference"
    case contractViolation = "contract_violation"
    case stateQuery = "state_query"
    case capabilityQuery = "capability_query"
    case cancelTooLate = "cancel_too_late"

    public init(finiteReason: RuntimeFiniteReason) {
        self = RuntimePresentationReasonAuthority.projection(for: finiteReason).safeReasonKind
    }

    public init?(finiteReason: String) {
        guard let projection = RuntimePresentationReasonAuthority.projection(forFiniteReason: finiteReason) else {
            return nil
        }
        self = projection.safeReasonKind
    }
}

public struct RuntimePresentationReasonProjection: Equatable, Sendable {
    public let safeReasonKind: RuntimePresentationSafeReasonKind
    public let result: DemoRuntimeResult
}

public enum RuntimePresentationReasonAuthority {
    public static let finiteReasons: [RuntimeFiniteReason] = RuntimeFiniteReason.allCases
    public static let finiteReasonRawValues: [String] = finiteReasons.map(\.rawValue)

    private static let projections: [RuntimeFiniteReason: RuntimePresentationReasonProjection] = [
        .safetyOrPolicyRefusal: RuntimePresentationReasonProjection(
            safeReasonKind: .safetyPolicy,
            result: .refusalSafetyOrPolicy
        ),
        .clarifyMissingSlot: RuntimePresentationReasonProjection(
            safeReasonKind: .clarificationRequired,
            result: .clarifyMissingSlot
        ),
        .unmountedToolName: RuntimePresentationReasonProjection(
            safeReasonKind: .capabilityNotMounted,
            result: .refusalNoAvailableTool
        ),
        .nameRejected: RuntimePresentationReasonProjection(
            safeReasonKind: .capabilityNotMounted,
            result: .refusalNoAvailableTool
        ),
        .fastPathNoMatch: RuntimePresentationReasonProjection(
            safeReasonKind: .notAvailableInDemo,
            result: .refusalNoAvailableTool
        ),
        .unsupportedToolPlan: RuntimePresentationReasonProjection(
            safeReasonKind: .notAvailableInDemo,
            result: .refusalNoAvailableTool
        ),
        .noRepresentativeTool: RuntimePresentationReasonProjection(
            safeReasonKind: .notAvailableInDemo,
            result: .refusalNoAvailableTool
        ),
        .runtimeExecutionError: RuntimePresentationReasonProjection(
            safeReasonKind: .runtimeUnavailable,
            result: .runtimeError
        ),
        .staleStateRevision: RuntimePresentationReasonProjection(
            safeReasonKind: .runtimeUnavailable,
            result: .runtimeError
        ),
        .alreadyStateNoop: RuntimePresentationReasonProjection(
            safeReasonKind: .alreadyDone,
            result: .alreadyStateNoop
        ),
        .lexicalInvalid: RuntimePresentationReasonProjection(
            safeReasonKind: .lexicalInvalid,
            result: .refusalContractViolation
        ),
        .numericOverflow: RuntimePresentationReasonProjection(
            safeReasonKind: .numericOverflow,
            result: .refusalContractViolation
        ),
        .arithmeticOverflow: RuntimePresentationReasonProjection(
            safeReasonKind: .numericOverflow,
            result: .refusalContractViolation
        ),
        .unsupportedPrecision: RuntimePresentationReasonProjection(
            safeReasonKind: .unsupportedPrecision,
            result: .refusalContractViolation
        ),
        .outOfRange: RuntimePresentationReasonProjection(
            safeReasonKind: .outOfRange,
            result: .refusalContractViolation
        ),
        .malformedCurrent: RuntimePresentationReasonProjection(
            safeReasonKind: .malformedCurrent,
            result: .refusalContractViolation
        ),
        .unsupportedUnitReference: RuntimePresentationReasonProjection(
            safeReasonKind: .unsupportedUnitReference,
            result: .refusalContractViolation
        ),
        .contractViolation: RuntimePresentationReasonProjection(
            safeReasonKind: .contractViolation,
            result: .refusalContractViolation
        ),
        .stateQuery: RuntimePresentationReasonProjection(
            safeReasonKind: .stateQuery,
            result: .stateQuery
        ),
        .capabilityQuery: RuntimePresentationReasonProjection(
            safeReasonKind: .capabilityQuery,
            result: .capabilityQuery
        ),
        .cancelTooLate: RuntimePresentationReasonProjection(
            safeReasonKind: .cancelTooLate,
            result: .cancelled
        ),
    ]

    private static let fallbackBuckets: [RuntimeFiniteReason: FallbackGovernanceReason] = [
        .safetyOrPolicyRefusal: .safetyOrClarifyReject,
        .clarifyMissingSlot: .safetyOrClarifyReject,
        .unmountedToolName: .unmountedNameRejected,
        .nameRejected: .unmountedNameRejected,
        .fastPathNoMatch: .fastPathNoMatchFallback,
        .unsupportedToolPlan: .fastPathNoMatchFallback,
        .noRepresentativeTool: .unknownNoRepresentativeEntry,
    ]

    public static func projection(for finiteReason: RuntimeFiniteReason) -> RuntimePresentationReasonProjection {
        projections[finiteReason]!
    }

    public static func projection(forFiniteReason finiteReason: String) -> RuntimePresentationReasonProjection? {
        RuntimeFiniteReason(rawValue: finiteReason).map(projection(for:))
    }

    static func fallbackBucket(for finiteReason: RuntimeFiniteReason) -> FallbackGovernanceReason? {
        fallbackBuckets[finiteReason]
    }
}
