// Generated by Tools/generate_fallback_script_catalog_swift.py. Do not edit.
// Source SHA-256: 5c6969f2b5db2ff57b3234a5589848dd62b32d011b1f5dcebfda8809153b94ea
// T0 registry SHA-256: e42c288796ac1e40763854486c96658cf7f76bc585f3f0cfd84f773e1c59e160

public enum FallbackScriptFamily: String, CaseIterable, Codable, Hashable, Sendable {
    case ac = "ac"
    case seat = "seat"
    case window = "window"
    case door = "door"
    case ambient = "ambient"
    case screen = "screen"
    case volume = "volume"
    case wiper = "wiper"
    case sunroofShade = "sunroofShade"
    case fragrance = "fragrance"
}

internal enum FallbackGovernanceReason: String, CaseIterable, Hashable, Sendable {
    case safetyOrClarifyReject = "safety_or_clarify_reject"
    case unmountedNameRejected = "unmounted_name_rejected"
    case fastPathNoMatchFallback = "fast_path_no_match_fallback"
    case unknownNoRepresentativeEntry = "unknown_no_representative_entry"
}

public enum FallbackSafeReasonKind: String, CaseIterable, Codable, Hashable, Sendable {
    case safetyPolicy = "safety_policy"
    case clarificationRequired = "clarification_required"
    case capabilityNotMounted = "capability_not_mounted"
    case notAvailableInDemo = "not_available_in_demo"
}

public enum FallbackResultKind: String, CaseIterable, Codable, Hashable, Sendable {
    case refusalSafetyOrPolicy = "refusal_safety_or_policy"
    case clarifyMissingSlot = "clarify_missing_slot"
    case refusalNoAvailableTool = "refusal_no_available_tool"
}

public struct FallbackScriptCatalogEntry: Codable, Equatable, Hashable, Sendable {
    public let cellID: String
    public let locale: String
    public let family: FallbackScriptFamily
    public let familyLabel: String
    public let resultKind: FallbackResultKind
    public let safeReasonKind: FallbackSafeReasonKind
    public let dialogText: String
    public let ttsText: String
    public let badgeLabel: String
}

public enum FallbackScriptCatalog {
    public static let sourceSHA256 = "5c6969f2b5db2ff57b3234a5589848dd62b32d011b1f5dcebfda8809153b94ea"
    private static let familyAliases: [String: FallbackScriptFamily] = [
        "ac": .ac,
        "air_conditioner": .ac,
        "ambient": .ambient,
        "ambient_light": .ambient,
        "door": .door,
        "fragrance": .fragrance,
        "screen": .screen,
        "seat": .seat,
        "sunroofShade": .sunroofShade,
        "sunroof_shade": .sunroofShade,
        "volume": .volume,
        "window": .window,
        "wiper": .wiper,
    ]

    public static func normalizeFamily(_ rawValue: String) -> FallbackScriptFamily? {
        familyAliases[rawValue]
    }

    public static let entries: [FallbackScriptCatalogEntry] = [
        FallbackScriptCatalogEntry(
            cellID: "fallback.ac.01.zh-CN",
            locale: "zh-CN",
            family: .ac,
            familyLabel: "空调",
            resultKind: .clarifyMissingSlot,
            safeReasonKind: .clarificationRequired,
            dialogText: "请先确认温区或目标温度，我先保持空调状态不变。",
            ttsText: "请先确认温区或目标温度，我先保持空调状态不变。",
            badgeLabel: "需确认"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.ac.02.zh-CN",
            locale: "zh-CN",
            family: .ac,
            familyLabel: "空调",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .capabilityNotMounted,
            dialogText: "这项空调控制暂未接入演示版，我先不改车内状态。",
            ttsText: "这项空调控制暂未接入演示版，我先不改车内状态。",
            badgeLabel: "暂未接入"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.ac.03.zh-CN",
            locale: "zh-CN",
            family: .ac,
            familyLabel: "空调",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这个空调说法还没稳稳接住，您可以说空调调到26度。",
            ttsText: "这个空调说法还没稳稳接住，您可以说空调调到26度。",
            badgeLabel: "换个说法"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.ac.04.zh-CN",
            locale: "zh-CN",
            family: .ac,
            familyLabel: "空调",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这类空调能力不在本轮演示范围，我先保持原样。",
            ttsText: "这类空调能力不在本轮演示范围，我先保持原样。",
            badgeLabel: "不在范围"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.seat.05.zh-CN",
            locale: "zh-CN",
            family: .seat,
            familyLabel: "座椅",
            resultKind: .clarifyMissingSlot,
            safeReasonKind: .clarificationRequired,
            dialogText: "座椅动作需要确认位置，我先保持座椅不动。",
            ttsText: "座椅动作需要确认位置，我先保持座椅不动。",
            badgeLabel: "需确认"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.seat.06.zh-CN",
            locale: "zh-CN",
            family: .seat,
            familyLabel: "座椅",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .capabilityNotMounted,
            dialogText: "座椅控制暂未接入演示版，我先不移动座椅。",
            ttsText: "座椅控制暂未接入演示版，我先不移动座椅。",
            badgeLabel: "暂未接入"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.seat.07.zh-CN",
            locale: "zh-CN",
            family: .seat,
            familyLabel: "座椅",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这个座椅说法还没稳稳接住，您可以说主驾座椅加热打开。",
            ttsText: "这个座椅说法还没稳稳接住，您可以说主驾座椅加热打开。",
            badgeLabel: "换个说法"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.seat.08.zh-CN",
            locale: "zh-CN",
            family: .seat,
            familyLabel: "座椅",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这类座椅能力不在本轮演示范围，我先保持原样。",
            ttsText: "这类座椅能力不在本轮演示范围，我先保持原样。",
            badgeLabel: "不在范围"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.window.09.zh-CN",
            locale: "zh-CN",
            family: .window,
            familyLabel: "车窗",
            resultKind: .clarifyMissingSlot,
            safeReasonKind: .clarificationRequired,
            dialogText: "车窗动作需要确认位置和开度，我先保持车窗不变。",
            ttsText: "车窗动作需要确认位置和开度，我先保持车窗不变。",
            badgeLabel: "需确认"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.window.10.zh-CN",
            locale: "zh-CN",
            family: .window,
            familyLabel: "车窗",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .capabilityNotMounted,
            dialogText: "车窗控制暂未接入演示版，我先不动车窗。",
            ttsText: "车窗控制暂未接入演示版，我先不动车窗。",
            badgeLabel: "暂未接入"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.window.11.zh-CN",
            locale: "zh-CN",
            family: .window,
            familyLabel: "车窗",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这个车窗说法还没稳稳接住，您可以说主驾车窗打开一半。",
            ttsText: "这个车窗说法还没稳稳接住，您可以说主驾车窗打开一半。",
            badgeLabel: "换个说法"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.window.12.zh-CN",
            locale: "zh-CN",
            family: .window,
            familyLabel: "车窗",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这类车窗能力不在本轮演示范围，我先保持原样。",
            ttsText: "这类车窗能力不在本轮演示范围，我先保持原样。",
            badgeLabel: "不在范围"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.door.13.zh-CN",
            locale: "zh-CN",
            family: .door,
            familyLabel: "车门",
            resultKind: .refusalSafetyOrPolicy,
            safeReasonKind: .safetyPolicy,
            dialogText: "行驶中为了安全不能开门；停稳后请再说一次，我先保持车门不变。",
            ttsText: "行驶中为了安全不能开门；停稳后请再说一次，我先保持车门不变。",
            badgeLabel: "安全拦截"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.door.14.zh-CN",
            locale: "zh-CN",
            family: .door,
            familyLabel: "车门",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .capabilityNotMounted,
            dialogText: "车门控制暂未接入演示版，我先不动车门。",
            ttsText: "车门控制暂未接入演示版，我先不动车门。",
            badgeLabel: "暂未接入"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.door.15.zh-CN",
            locale: "zh-CN",
            family: .door,
            familyLabel: "车门",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这个车门说法还没稳稳接住，我先保持车门状态不变。",
            ttsText: "这个车门说法还没稳稳接住，我先保持车门状态不变。",
            badgeLabel: "换个说法"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.door.16.zh-CN",
            locale: "zh-CN",
            family: .door,
            familyLabel: "车门",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这类车门能力不在本轮演示范围，我先保持原样。",
            ttsText: "这类车门能力不在本轮演示范围，我先保持原样。",
            badgeLabel: "不在范围"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.ambient.17.zh-CN",
            locale: "zh-CN",
            family: .ambient,
            familyLabel: "氛围灯",
            resultKind: .clarifyMissingSlot,
            safeReasonKind: .clarificationRequired,
            dialogText: "氛围灯效果需要确认颜色或亮度，我先保持灯光不变。",
            ttsText: "氛围灯效果需要确认颜色或亮度，我先保持灯光不变。",
            badgeLabel: "需确认"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.ambient.18.zh-CN",
            locale: "zh-CN",
            family: .ambient,
            familyLabel: "氛围灯",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .capabilityNotMounted,
            dialogText: "氛围灯控制暂未接入演示版，我先不改灯光。",
            ttsText: "氛围灯控制暂未接入演示版，我先不改灯光。",
            badgeLabel: "暂未接入"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.ambient.19.zh-CN",
            locale: "zh-CN",
            family: .ambient,
            familyLabel: "氛围灯",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这个氛围灯说法还没稳稳接住，您可以说氛围灯调亮一点。",
            ttsText: "这个氛围灯说法还没稳稳接住，您可以说氛围灯调亮一点。",
            badgeLabel: "换个说法"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.ambient.20.zh-CN",
            locale: "zh-CN",
            family: .ambient,
            familyLabel: "氛围灯",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这类氛围灯能力不在本轮演示范围，我先保持原样。",
            ttsText: "这类氛围灯能力不在本轮演示范围，我先保持原样。",
            badgeLabel: "不在范围"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.screen.21.zh-CN",
            locale: "zh-CN",
            family: .screen,
            familyLabel: "屏幕",
            resultKind: .clarifyMissingSlot,
            safeReasonKind: .clarificationRequired,
            dialogText: "屏幕设置需要确认目标屏幕，我先保持显示不变。",
            ttsText: "屏幕设置需要确认目标屏幕，我先保持显示不变。",
            badgeLabel: "需确认"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.screen.22.zh-CN",
            locale: "zh-CN",
            family: .screen,
            familyLabel: "屏幕",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .capabilityNotMounted,
            dialogText: "屏幕控制暂未接入演示版，我先不改屏幕设置。",
            ttsText: "屏幕控制暂未接入演示版，我先不改屏幕设置。",
            badgeLabel: "暂未接入"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.screen.23.zh-CN",
            locale: "zh-CN",
            family: .screen,
            familyLabel: "屏幕",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这个屏幕说法还没稳稳接住，您可以说中控屏亮度调高。",
            ttsText: "这个屏幕说法还没稳稳接住，您可以说中控屏亮度调高。",
            badgeLabel: "换个说法"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.screen.24.zh-CN",
            locale: "zh-CN",
            family: .screen,
            familyLabel: "屏幕",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这类屏幕能力不在本轮演示范围，我先保持原样。",
            ttsText: "这类屏幕能力不在本轮演示范围，我先保持原样。",
            badgeLabel: "不在范围"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.volume.25.zh-CN",
            locale: "zh-CN",
            family: .volume,
            familyLabel: "音量",
            resultKind: .clarifyMissingSlot,
            safeReasonKind: .clarificationRequired,
            dialogText: "音量变化需要确认方向，我先保持当前音量。",
            ttsText: "音量变化需要确认方向，我先保持当前音量。",
            badgeLabel: "需确认"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.volume.26.zh-CN",
            locale: "zh-CN",
            family: .volume,
            familyLabel: "音量",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .capabilityNotMounted,
            dialogText: "音量控制暂未接入演示版，我先不改音量。",
            ttsText: "音量控制暂未接入演示版，我先不改音量。",
            badgeLabel: "暂未接入"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.volume.27.zh-CN",
            locale: "zh-CN",
            family: .volume,
            familyLabel: "音量",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这个音量说法还没稳稳接住，您可以说音量调低一点。",
            ttsText: "这个音量说法还没稳稳接住，您可以说音量调低一点。",
            badgeLabel: "换个说法"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.volume.28.zh-CN",
            locale: "zh-CN",
            family: .volume,
            familyLabel: "音量",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这类音量能力不在本轮演示范围，我先保持原样。",
            ttsText: "这类音量能力不在本轮演示范围，我先保持原样。",
            badgeLabel: "不在范围"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.wiper.29.zh-CN",
            locale: "zh-CN",
            family: .wiper,
            familyLabel: "雨刮",
            resultKind: .clarifyMissingSlot,
            safeReasonKind: .clarificationRequired,
            dialogText: "雨刮动作需要确认模式或速度，我先保持雨刮不变。",
            ttsText: "雨刮动作需要确认模式或速度，我先保持雨刮不变。",
            badgeLabel: "需确认"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.wiper.30.zh-CN",
            locale: "zh-CN",
            family: .wiper,
            familyLabel: "雨刮",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .capabilityNotMounted,
            dialogText: "雨刮控制暂未接入演示版，我先不动雨刮。",
            ttsText: "雨刮控制暂未接入演示版，我先不动雨刮。",
            badgeLabel: "暂未接入"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.wiper.31.zh-CN",
            locale: "zh-CN",
            family: .wiper,
            familyLabel: "雨刮",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这个雨刮说法还没稳稳接住，您可以说打开雨刮。",
            ttsText: "这个雨刮说法还没稳稳接住，您可以说打开雨刮。",
            badgeLabel: "换个说法"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.wiper.32.zh-CN",
            locale: "zh-CN",
            family: .wiper,
            familyLabel: "雨刮",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这类雨刮能力不在本轮演示范围，我先保持原样。",
            ttsText: "这类雨刮能力不在本轮演示范围，我先保持原样。",
            badgeLabel: "不在范围"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.sunroofShade.33.zh-CN",
            locale: "zh-CN",
            family: .sunroofShade,
            familyLabel: "天窗遮阳",
            resultKind: .clarifyMissingSlot,
            safeReasonKind: .clarificationRequired,
            dialogText: "天窗遮阳需要确认部件和开度，我先保持当前位置。",
            ttsText: "天窗遮阳需要确认部件和开度，我先保持当前位置。",
            badgeLabel: "需确认"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.sunroofShade.34.zh-CN",
            locale: "zh-CN",
            family: .sunroofShade,
            familyLabel: "天窗遮阳",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .capabilityNotMounted,
            dialogText: "天窗遮阳控制暂未接入演示版，我先不动车顶部件。",
            ttsText: "天窗遮阳控制暂未接入演示版，我先不动车顶部件。",
            badgeLabel: "暂未接入"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.sunroofShade.35.zh-CN",
            locale: "zh-CN",
            family: .sunroofShade,
            familyLabel: "天窗遮阳",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这个天窗遮阳说法还没稳稳接住，您可以说打开天窗遮阳帘。",
            ttsText: "这个天窗遮阳说法还没稳稳接住，您可以说打开天窗遮阳帘。",
            badgeLabel: "换个说法"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.sunroofShade.36.zh-CN",
            locale: "zh-CN",
            family: .sunroofShade,
            familyLabel: "天窗遮阳",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这类车顶部件不在本轮演示范围，我先保持原样。",
            ttsText: "这类车顶部件不在本轮演示范围，我先保持原样。",
            badgeLabel: "不在范围"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.fragrance.37.zh-CN",
            locale: "zh-CN",
            family: .fragrance,
            familyLabel: "香氛",
            resultKind: .clarifyMissingSlot,
            safeReasonKind: .clarificationRequired,
            dialogText: "香氛设置需要确认模式或浓度，我先保持当前香氛。",
            ttsText: "香氛设置需要确认模式或浓度，我先保持当前香氛。",
            badgeLabel: "需确认"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.fragrance.38.zh-CN",
            locale: "zh-CN",
            family: .fragrance,
            familyLabel: "香氛",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .capabilityNotMounted,
            dialogText: "香氛控制暂未接入演示版，我先不改香氛设置。",
            ttsText: "香氛控制暂未接入演示版，我先不改香氛设置。",
            badgeLabel: "暂未接入"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.fragrance.39.zh-CN",
            locale: "zh-CN",
            family: .fragrance,
            familyLabel: "香氛",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这个香氛说法还没稳稳接住，您可以说打开香氛。",
            ttsText: "这个香氛说法还没稳稳接住，您可以说打开香氛。",
            badgeLabel: "换个说法"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.fragrance.40.zh-CN",
            locale: "zh-CN",
            family: .fragrance,
            familyLabel: "香氛",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这类香氛能力不在本轮演示范围，我先保持原样。",
            ttsText: "这类香氛能力不在本轮演示范围，我先保持原样。",
            badgeLabel: "不在范围"
        ),
    ]

    private static let governanceReasons: [String: FallbackGovernanceReason] = [
        "fallback.ac.01.zh-CN": .safetyOrClarifyReject,
        "fallback.ac.02.zh-CN": .unmountedNameRejected,
        "fallback.ac.03.zh-CN": .fastPathNoMatchFallback,
        "fallback.ac.04.zh-CN": .unknownNoRepresentativeEntry,
        "fallback.seat.05.zh-CN": .safetyOrClarifyReject,
        "fallback.seat.06.zh-CN": .unmountedNameRejected,
        "fallback.seat.07.zh-CN": .fastPathNoMatchFallback,
        "fallback.seat.08.zh-CN": .unknownNoRepresentativeEntry,
        "fallback.window.09.zh-CN": .safetyOrClarifyReject,
        "fallback.window.10.zh-CN": .unmountedNameRejected,
        "fallback.window.11.zh-CN": .fastPathNoMatchFallback,
        "fallback.window.12.zh-CN": .unknownNoRepresentativeEntry,
        "fallback.door.13.zh-CN": .safetyOrClarifyReject,
        "fallback.door.14.zh-CN": .unmountedNameRejected,
        "fallback.door.15.zh-CN": .fastPathNoMatchFallback,
        "fallback.door.16.zh-CN": .unknownNoRepresentativeEntry,
        "fallback.ambient.17.zh-CN": .safetyOrClarifyReject,
        "fallback.ambient.18.zh-CN": .unmountedNameRejected,
        "fallback.ambient.19.zh-CN": .fastPathNoMatchFallback,
        "fallback.ambient.20.zh-CN": .unknownNoRepresentativeEntry,
        "fallback.screen.21.zh-CN": .safetyOrClarifyReject,
        "fallback.screen.22.zh-CN": .unmountedNameRejected,
        "fallback.screen.23.zh-CN": .fastPathNoMatchFallback,
        "fallback.screen.24.zh-CN": .unknownNoRepresentativeEntry,
        "fallback.volume.25.zh-CN": .safetyOrClarifyReject,
        "fallback.volume.26.zh-CN": .unmountedNameRejected,
        "fallback.volume.27.zh-CN": .fastPathNoMatchFallback,
        "fallback.volume.28.zh-CN": .unknownNoRepresentativeEntry,
        "fallback.wiper.29.zh-CN": .safetyOrClarifyReject,
        "fallback.wiper.30.zh-CN": .unmountedNameRejected,
        "fallback.wiper.31.zh-CN": .fastPathNoMatchFallback,
        "fallback.wiper.32.zh-CN": .unknownNoRepresentativeEntry,
        "fallback.sunroofShade.33.zh-CN": .safetyOrClarifyReject,
        "fallback.sunroofShade.34.zh-CN": .unmountedNameRejected,
        "fallback.sunroofShade.35.zh-CN": .fastPathNoMatchFallback,
        "fallback.sunroofShade.36.zh-CN": .unknownNoRepresentativeEntry,
        "fallback.fragrance.37.zh-CN": .safetyOrClarifyReject,
        "fallback.fragrance.38.zh-CN": .unmountedNameRejected,
        "fallback.fragrance.39.zh-CN": .fastPathNoMatchFallback,
        "fallback.fragrance.40.zh-CN": .unknownNoRepresentativeEntry,
    ]

    /// Internal lookup for Core consumers; governance reason never enters the Codable entry.
    static func governanceReason(for entry: FallbackScriptCatalogEntry) -> FallbackGovernanceReason? {
        governanceReasons[entry.cellID]
    }

    static func entry(for family: FallbackScriptFamily, governanceReason: FallbackGovernanceReason) -> FallbackScriptCatalogEntry? {
        entries.first { $0.family == family && governanceReasons[$0.cellID] == governanceReason }
    }
}
