// Generated by Tools/generate_fallback_script_catalog_swift.py. Do not edit.
// Source SHA-256: b22ead6468d79f81f8fb04a8199917de89a279972a1618d76e055efe48fd8b0b

public enum FallbackScriptFamily: String, CaseIterable, Codable, Hashable, Sendable {
    case ac = "ac"
    case seat = "seat"
    case window = "window"
    case door = "door"
    case ambient = "ambient"
    case screen = "screen"
    case volume = "volume"
    case wiper = "wiper"
    case sunroofShade = "sunroofShade"
    case fragrance = "fragrance"
}

public enum FallbackGovernanceReason: String, CaseIterable, Codable, Hashable, Sendable {
    case safetyOrClarifyReject = "safety_or_clarify_reject"
    case unmountedNameRejected = "unmounted_name_rejected"
    case fastPathNoMatchFallback = "fast_path_no_match_fallback"
    case unknownNoRepresentativeEntry = "unknown_no_representative_entry"
}

public enum FallbackSafeReasonKind: String, CaseIterable, Codable, Hashable, Sendable {
    case safetyPolicy = "safety_policy"
    case clarificationRequired = "clarification_required"
    case capabilityNotMounted = "capability_not_mounted"
    case notAvailableInDemo = "not_available_in_demo"
}

public enum FallbackResultKind: String, CaseIterable, Codable, Hashable, Sendable {
    case refusalSafetyOrPolicy = "refusal_safety_or_policy"
    case clarifyMissingSlot = "clarify_missing_slot"
    case refusalNoAvailableTool = "refusal_no_available_tool"
}

public struct FallbackScriptCatalogEntry: Codable, Equatable, Hashable, Sendable {
    public let cellID: String
    public let locale: String
    public let family: FallbackScriptFamily
    public let familyLabel: String
    public let resultKind: FallbackResultKind
    public let safeReasonKind: FallbackSafeReasonKind
    public let dialogText: String
    public let ttsText: String
    public let badgeLabel: String
}

public enum FallbackScriptCatalog {
    public static let sourceSHA256 = "b22ead6468d79f81f8fb04a8199917de89a279972a1618d76e055efe48fd8b0b"
    private static let familyAliases: [String: FallbackScriptFamily] = [
        "ac": .ac,
        "air_conditioner": .ac,
        "ambient": .ambient,
        "ambient_light": .ambient,
        "door": .door,
        "fragrance": .fragrance,
        "screen": .screen,
        "seat": .seat,
        "sunroofShade": .sunroofShade,
        "sunroof_shade": .sunroofShade,
        "volume": .volume,
        "window": .window,
        "wiper": .wiper,
    ]

    public static func normalizeFamily(_ rawValue: String) -> FallbackScriptFamily? {
        familyAliases[rawValue]
    }

    public static let entries: [FallbackScriptCatalogEntry] = [
        FallbackScriptCatalogEntry(
            cellID: "fallback.ac.safety_or_clarify_reject.zh-CN",
            locale: "zh-CN",
            family: .ac,
            familyLabel: "空调",
            resultKind: .clarifyMissingSlot,
            safeReasonKind: .clarificationRequired,
            dialogText: "请先确认温区或目标温度，我先保持空调状态不变。",
            ttsText: "请先确认温区或目标温度，我先保持空调状态不变。",
            badgeLabel: "需确认"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.ac.unmounted_name_rejected.zh-CN",
            locale: "zh-CN",
            family: .ac,
            familyLabel: "空调",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .capabilityNotMounted,
            dialogText: "这项空调控制暂未接入演示版，我先不改车内状态。",
            ttsText: "这项空调控制暂未接入演示版，我先不改车内状态。",
            badgeLabel: "暂未接入"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.ac.fast_path_no_match_fallback.zh-CN",
            locale: "zh-CN",
            family: .ac,
            familyLabel: "空调",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这个空调说法还没稳稳接住，您可以说空调调到26度。",
            ttsText: "这个空调说法还没稳稳接住，您可以说空调调到26度。",
            badgeLabel: "换个说法"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.ac.unknown_no_representative_entry.zh-CN",
            locale: "zh-CN",
            family: .ac,
            familyLabel: "空调",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这类空调能力不在本轮演示范围，我先保持原样。",
            ttsText: "这类空调能力不在本轮演示范围，我先保持原样。",
            badgeLabel: "不在范围"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.seat.safety_or_clarify_reject.zh-CN",
            locale: "zh-CN",
            family: .seat,
            familyLabel: "座椅",
            resultKind: .clarifyMissingSlot,
            safeReasonKind: .clarificationRequired,
            dialogText: "座椅动作需要确认位置，我先保持座椅不动。",
            ttsText: "座椅动作需要确认位置，我先保持座椅不动。",
            badgeLabel: "需确认"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.seat.unmounted_name_rejected.zh-CN",
            locale: "zh-CN",
            family: .seat,
            familyLabel: "座椅",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .capabilityNotMounted,
            dialogText: "座椅控制暂未接入演示版，我先不移动座椅。",
            ttsText: "座椅控制暂未接入演示版，我先不移动座椅。",
            badgeLabel: "暂未接入"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.seat.fast_path_no_match_fallback.zh-CN",
            locale: "zh-CN",
            family: .seat,
            familyLabel: "座椅",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这个座椅说法还没稳稳接住，您可以说主驾座椅加热打开。",
            ttsText: "这个座椅说法还没稳稳接住，您可以说主驾座椅加热打开。",
            badgeLabel: "换个说法"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.seat.unknown_no_representative_entry.zh-CN",
            locale: "zh-CN",
            family: .seat,
            familyLabel: "座椅",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这类座椅能力不在本轮演示范围，我先保持原样。",
            ttsText: "这类座椅能力不在本轮演示范围，我先保持原样。",
            badgeLabel: "不在范围"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.window.safety_or_clarify_reject.zh-CN",
            locale: "zh-CN",
            family: .window,
            familyLabel: "车窗",
            resultKind: .clarifyMissingSlot,
            safeReasonKind: .clarificationRequired,
            dialogText: "车窗动作需要确认位置和开度，我先保持车窗不变。",
            ttsText: "车窗动作需要确认位置和开度，我先保持车窗不变。",
            badgeLabel: "需确认"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.window.unmounted_name_rejected.zh-CN",
            locale: "zh-CN",
            family: .window,
            familyLabel: "车窗",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .capabilityNotMounted,
            dialogText: "车窗控制暂未接入演示版，我先不动车窗。",
            ttsText: "车窗控制暂未接入演示版，我先不动车窗。",
            badgeLabel: "暂未接入"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.window.fast_path_no_match_fallback.zh-CN",
            locale: "zh-CN",
            family: .window,
            familyLabel: "车窗",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这个车窗说法还没稳稳接住，您可以说主驾车窗打开一半。",
            ttsText: "这个车窗说法还没稳稳接住，您可以说主驾车窗打开一半。",
            badgeLabel: "换个说法"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.window.unknown_no_representative_entry.zh-CN",
            locale: "zh-CN",
            family: .window,
            familyLabel: "车窗",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这类车窗能力不在本轮演示范围，我先保持原样。",
            ttsText: "这类车窗能力不在本轮演示范围，我先保持原样。",
            badgeLabel: "不在范围"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.door.safety_or_clarify_reject.zh-CN",
            locale: "zh-CN",
            family: .door,
            familyLabel: "车门",
            resultKind: .refusalSafetyOrPolicy,
            safeReasonKind: .safetyPolicy,
            dialogText: "行驶中为了安全不能开门；停稳后请再说一次，我先保持车门不变。",
            ttsText: "行驶中为了安全不能开门；停稳后请再说一次，我先保持车门不变。",
            badgeLabel: "安全拦截"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.door.unmounted_name_rejected.zh-CN",
            locale: "zh-CN",
            family: .door,
            familyLabel: "车门",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .capabilityNotMounted,
            dialogText: "车门控制暂未接入演示版，我先不动车门。",
            ttsText: "车门控制暂未接入演示版，我先不动车门。",
            badgeLabel: "暂未接入"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.door.fast_path_no_match_fallback.zh-CN",
            locale: "zh-CN",
            family: .door,
            familyLabel: "车门",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这个车门说法还没稳稳接住，我先保持车门状态不变。",
            ttsText: "这个车门说法还没稳稳接住，我先保持车门状态不变。",
            badgeLabel: "换个说法"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.door.unknown_no_representative_entry.zh-CN",
            locale: "zh-CN",
            family: .door,
            familyLabel: "车门",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这类车门能力不在本轮演示范围，我先保持原样。",
            ttsText: "这类车门能力不在本轮演示范围，我先保持原样。",
            badgeLabel: "不在范围"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.ambient.safety_or_clarify_reject.zh-CN",
            locale: "zh-CN",
            family: .ambient,
            familyLabel: "氛围灯",
            resultKind: .clarifyMissingSlot,
            safeReasonKind: .clarificationRequired,
            dialogText: "氛围灯效果需要确认颜色或亮度，我先保持灯光不变。",
            ttsText: "氛围灯效果需要确认颜色或亮度，我先保持灯光不变。",
            badgeLabel: "需确认"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.ambient.unmounted_name_rejected.zh-CN",
            locale: "zh-CN",
            family: .ambient,
            familyLabel: "氛围灯",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .capabilityNotMounted,
            dialogText: "氛围灯控制暂未接入演示版，我先不改灯光。",
            ttsText: "氛围灯控制暂未接入演示版，我先不改灯光。",
            badgeLabel: "暂未接入"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.ambient.fast_path_no_match_fallback.zh-CN",
            locale: "zh-CN",
            family: .ambient,
            familyLabel: "氛围灯",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这个氛围灯说法还没稳稳接住，您可以说氛围灯调亮一点。",
            ttsText: "这个氛围灯说法还没稳稳接住，您可以说氛围灯调亮一点。",
            badgeLabel: "换个说法"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.ambient.unknown_no_representative_entry.zh-CN",
            locale: "zh-CN",
            family: .ambient,
            familyLabel: "氛围灯",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这类氛围灯能力不在本轮演示范围，我先保持原样。",
            ttsText: "这类氛围灯能力不在本轮演示范围，我先保持原样。",
            badgeLabel: "不在范围"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.screen.safety_or_clarify_reject.zh-CN",
            locale: "zh-CN",
            family: .screen,
            familyLabel: "屏幕",
            resultKind: .clarifyMissingSlot,
            safeReasonKind: .clarificationRequired,
            dialogText: "屏幕设置需要确认目标屏幕，我先保持显示不变。",
            ttsText: "屏幕设置需要确认目标屏幕，我先保持显示不变。",
            badgeLabel: "需确认"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.screen.unmounted_name_rejected.zh-CN",
            locale: "zh-CN",
            family: .screen,
            familyLabel: "屏幕",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .capabilityNotMounted,
            dialogText: "屏幕控制暂未接入演示版，我先不改屏幕设置。",
            ttsText: "屏幕控制暂未接入演示版，我先不改屏幕设置。",
            badgeLabel: "暂未接入"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.screen.fast_path_no_match_fallback.zh-CN",
            locale: "zh-CN",
            family: .screen,
            familyLabel: "屏幕",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这个屏幕说法还没稳稳接住，您可以说中控屏亮度调高。",
            ttsText: "这个屏幕说法还没稳稳接住，您可以说中控屏亮度调高。",
            badgeLabel: "换个说法"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.screen.unknown_no_representative_entry.zh-CN",
            locale: "zh-CN",
            family: .screen,
            familyLabel: "屏幕",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这类屏幕能力不在本轮演示范围，我先保持原样。",
            ttsText: "这类屏幕能力不在本轮演示范围，我先保持原样。",
            badgeLabel: "不在范围"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.volume.safety_or_clarify_reject.zh-CN",
            locale: "zh-CN",
            family: .volume,
            familyLabel: "音量",
            resultKind: .clarifyMissingSlot,
            safeReasonKind: .clarificationRequired,
            dialogText: "音量变化需要确认方向，我先保持当前音量。",
            ttsText: "音量变化需要确认方向，我先保持当前音量。",
            badgeLabel: "需确认"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.volume.unmounted_name_rejected.zh-CN",
            locale: "zh-CN",
            family: .volume,
            familyLabel: "音量",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .capabilityNotMounted,
            dialogText: "音量控制暂未接入演示版，我先不改音量。",
            ttsText: "音量控制暂未接入演示版，我先不改音量。",
            badgeLabel: "暂未接入"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.volume.fast_path_no_match_fallback.zh-CN",
            locale: "zh-CN",
            family: .volume,
            familyLabel: "音量",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这个音量说法还没稳稳接住，您可以说音量调低一点。",
            ttsText: "这个音量说法还没稳稳接住，您可以说音量调低一点。",
            badgeLabel: "换个说法"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.volume.unknown_no_representative_entry.zh-CN",
            locale: "zh-CN",
            family: .volume,
            familyLabel: "音量",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这类音量能力不在本轮演示范围，我先保持原样。",
            ttsText: "这类音量能力不在本轮演示范围，我先保持原样。",
            badgeLabel: "不在范围"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.wiper.safety_or_clarify_reject.zh-CN",
            locale: "zh-CN",
            family: .wiper,
            familyLabel: "雨刮",
            resultKind: .clarifyMissingSlot,
            safeReasonKind: .clarificationRequired,
            dialogText: "雨刮动作需要确认模式或速度，我先保持雨刮不变。",
            ttsText: "雨刮动作需要确认模式或速度，我先保持雨刮不变。",
            badgeLabel: "需确认"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.wiper.unmounted_name_rejected.zh-CN",
            locale: "zh-CN",
            family: .wiper,
            familyLabel: "雨刮",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .capabilityNotMounted,
            dialogText: "雨刮控制暂未接入演示版，我先不动雨刮。",
            ttsText: "雨刮控制暂未接入演示版，我先不动雨刮。",
            badgeLabel: "暂未接入"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.wiper.fast_path_no_match_fallback.zh-CN",
            locale: "zh-CN",
            family: .wiper,
            familyLabel: "雨刮",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这个雨刮说法还没稳稳接住，您可以说打开雨刮。",
            ttsText: "这个雨刮说法还没稳稳接住，您可以说打开雨刮。",
            badgeLabel: "换个说法"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.wiper.unknown_no_representative_entry.zh-CN",
            locale: "zh-CN",
            family: .wiper,
            familyLabel: "雨刮",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这类雨刮能力不在本轮演示范围，我先保持原样。",
            ttsText: "这类雨刮能力不在本轮演示范围，我先保持原样。",
            badgeLabel: "不在范围"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.sunroofShade.safety_or_clarify_reject.zh-CN",
            locale: "zh-CN",
            family: .sunroofShade,
            familyLabel: "天窗遮阳",
            resultKind: .clarifyMissingSlot,
            safeReasonKind: .clarificationRequired,
            dialogText: "天窗遮阳需要确认部件和开度，我先保持当前位置。",
            ttsText: "天窗遮阳需要确认部件和开度，我先保持当前位置。",
            badgeLabel: "需确认"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.sunroofShade.unmounted_name_rejected.zh-CN",
            locale: "zh-CN",
            family: .sunroofShade,
            familyLabel: "天窗遮阳",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .capabilityNotMounted,
            dialogText: "天窗遮阳控制暂未接入演示版，我先不动车顶部件。",
            ttsText: "天窗遮阳控制暂未接入演示版，我先不动车顶部件。",
            badgeLabel: "暂未接入"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.sunroofShade.fast_path_no_match_fallback.zh-CN",
            locale: "zh-CN",
            family: .sunroofShade,
            familyLabel: "天窗遮阳",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这个天窗遮阳说法还没稳稳接住，您可以说打开天窗遮阳帘。",
            ttsText: "这个天窗遮阳说法还没稳稳接住，您可以说打开天窗遮阳帘。",
            badgeLabel: "换个说法"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.sunroofShade.unknown_no_representative_entry.zh-CN",
            locale: "zh-CN",
            family: .sunroofShade,
            familyLabel: "天窗遮阳",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这类车顶部件不在本轮演示范围，我先保持原样。",
            ttsText: "这类车顶部件不在本轮演示范围，我先保持原样。",
            badgeLabel: "不在范围"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.fragrance.safety_or_clarify_reject.zh-CN",
            locale: "zh-CN",
            family: .fragrance,
            familyLabel: "香氛",
            resultKind: .clarifyMissingSlot,
            safeReasonKind: .clarificationRequired,
            dialogText: "香氛设置需要确认模式或浓度，我先保持当前香氛。",
            ttsText: "香氛设置需要确认模式或浓度，我先保持当前香氛。",
            badgeLabel: "需确认"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.fragrance.unmounted_name_rejected.zh-CN",
            locale: "zh-CN",
            family: .fragrance,
            familyLabel: "香氛",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .capabilityNotMounted,
            dialogText: "香氛控制暂未接入演示版，我先不改香氛设置。",
            ttsText: "香氛控制暂未接入演示版，我先不改香氛设置。",
            badgeLabel: "暂未接入"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.fragrance.fast_path_no_match_fallback.zh-CN",
            locale: "zh-CN",
            family: .fragrance,
            familyLabel: "香氛",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这个香氛说法还没稳稳接住，您可以说打开香氛。",
            ttsText: "这个香氛说法还没稳稳接住，您可以说打开香氛。",
            badgeLabel: "换个说法"
        ),
        FallbackScriptCatalogEntry(
            cellID: "fallback.fragrance.unknown_no_representative_entry.zh-CN",
            locale: "zh-CN",
            family: .fragrance,
            familyLabel: "香氛",
            resultKind: .refusalNoAvailableTool,
            safeReasonKind: .notAvailableInDemo,
            dialogText: "这类香氛能力不在本轮演示范围，我先保持原样。",
            ttsText: "这类香氛能力不在本轮演示范围，我先保持原样。",
            badgeLabel: "不在范围"
        ),
    ]
}
