schemaVersion: 1
sessionDefaultsProfiles:
  ios:
    projectPath: /Users/wanglei/workspace/MAformac/MAformac.xcodeproj
    scheme: MAformacIOS
    configuration: Debug
    simulatorName: iPhone 17 Pro
    useLatestOS: true
    simulatorPlatform: iOS Simulator
activeSessionDefaultsProfile: ios
