#!/usr/bin/env python3
"""Generate deterministic audit JSON and Swift lookup views from fallback-scripts.yaml."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


FAMILY_CASES = {
    "ac": "ac",
    "seat": "seat",
    "window": "window",
    "door": "door",
    "ambient": "ambient",
    "screen": "screen",
    "volume": "volume",
    "wiper": "wiper",
    "sunroofShade": "sunroofShade",
    "fragrance": "fragrance",
}
REASON_CASES = {
    "safety_or_clarify_reject": "safetyOrClarifyReject",
    "unmounted_name_rejected": "unmountedNameRejected",
    "fast_path_no_match_fallback": "fastPathNoMatchFallback",
    "unknown_no_representative_entry": "unknownNoRepresentativeEntry",
}
SAFE_CASES = {
    "safety_policy": "safetyPolicy",
    "clarification_required": "clarificationRequired",
    "capability_not_mounted": "capabilityNotMounted",
    "not_available_in_demo": "notAvailableInDemo",
}
RESULT_CASES = {
    "refusal_safety_or_policy": "refusalSafetyOrPolicy",
    "clarify_missing_slot": "clarifyMissingSlot",
    "refusal_no_available_tool": "refusalNoAvailableTool",
}


def swift_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def enum_source(name: str, values: list[str], cases: dict[str, str], visibility: str = "public", codable: bool = True) -> list[str]:
    protocols = "CaseIterable, Codable, Hashable, Sendable" if codable else "CaseIterable, Hashable, Sendable"
    lines = [f"{visibility} enum {name}: String, {protocols} {{"]
    lines.extend(f"    case {cases[value]} = {swift_string(value)}" for value in values)
    lines.append("}")
    return lines


def public_cell_id(source: dict, cell: dict) -> str:
    # Stable public identifier deliberately excludes governance vocabulary.
    index = source["cells"].index(cell) + 1
    return f"fallback.{cell['family']}.{index:02d}.{cell['locale']}"


def public_entry(source: dict, cell: dict) -> dict:
    family = cell["family"]
    return {
        "cellID": public_cell_id(source, cell),
        "locale": cell["locale"],
        "family": family,
        "familyLabel": source["families"][family]["familyLabel"],
        "resultKind": cell["result_kind"],
        "safeReasonKind": cell["safeReasonKind"],
        "dialogText": cell["dialogText"],
        "ttsText": cell["ttsText"],
        "badgeLabel": cell["badgeLabel"],
    }


def generate_swift(source: dict, source_sha: str) -> str:
    lines = [
        "// Generated by Tools/generate_fallback_script_catalog_swift.py. Do not edit.",
        f"// Source SHA-256: {source_sha}",
        "",
    ]
    lines.extend(enum_source("FallbackScriptFamily", source["family_enum"], FAMILY_CASES, "public"))
    lines.append("")
    lines.extend(enum_source("FallbackGovernanceReason", source["governance_reason_enum"], REASON_CASES, "internal", False))
    lines.append("")
    lines.extend(enum_source("FallbackSafeReasonKind", source["safe_reason_kind_enum"], SAFE_CASES, "public"))
    lines.append("")
    lines.extend(enum_source("FallbackResultKind", source["result_kind_enum"], RESULT_CASES, "public"))
    lines.extend(
        [
            "",
            "public struct FallbackScriptCatalogEntry: Codable, Equatable, Hashable, Sendable {",
            "    public let cellID: String",
            "    public let locale: String",
            "    public let family: FallbackScriptFamily",
            "    public let familyLabel: String",
            "    public let resultKind: FallbackResultKind",
            "    public let safeReasonKind: FallbackSafeReasonKind",
            "    public let dialogText: String",
            "    public let ttsText: String",
            "    public let badgeLabel: String",
            "}",
            "",
            "public enum FallbackScriptCatalog {",
            f"    public static let sourceSHA256 = {swift_string(source_sha)}",
            "    private static let familyAliases: [String: FallbackScriptFamily] = [",
        ]
    )
    aliases: list[tuple[str, str]] = []
    for family in source["family_enum"]:
        aliases.append((family, family))
        aliases.extend((alias, family) for alias in source["families"][family].get("aliases", []))
    for alias, family in sorted(aliases):
        lines.append(f"        {swift_string(alias)}: .{FAMILY_CASES[family]},")
    lines.extend(
        [
            "    ]",
            "",
            "    public static func normalizeFamily(_ rawValue: String) -> FallbackScriptFamily? {",
            "        familyAliases[rawValue]",
            "    }",
            "",
            "    public static let entries: [FallbackScriptCatalogEntry] = [",
        ]
    )
    for cell in source["cells"]:
        family = cell["family"]
        lines.extend(
            [
                "        FallbackScriptCatalogEntry(",
                f"            cellID: {swift_string(public_cell_id(source, cell))},",
                f"            locale: {swift_string(cell['locale'])},",
                f"            family: .{FAMILY_CASES[family]},",
                f"            familyLabel: {swift_string(source['families'][family]['familyLabel'])},",
                f"            resultKind: .{RESULT_CASES[cell['result_kind']]},",
                f"            safeReasonKind: .{SAFE_CASES[cell['safeReasonKind']]},",
                f"            dialogText: {swift_string(cell['dialogText'])},",
                f"            ttsText: {swift_string(cell['ttsText'])},",
                f"            badgeLabel: {swift_string(cell['badgeLabel'])}",
                "        ),",
            ]
        )
    lines.extend(["    ]", "", "    private static let governanceReasons: [String: FallbackGovernanceReason] = ["])
    for cell in source["cells"]:
        lines.append(f"        {swift_string(public_cell_id(source, cell))}: .{REASON_CASES[cell['reason_kind']]},")
    lines.extend([
        "    ]",
        "",
        "    /// Internal lookup for Core consumers; governance reason never enters the Codable entry.",
        "    static func governanceReason(for entry: FallbackScriptCatalogEntry) -> FallbackGovernanceReason? {",
        "        governanceReasons[entry.cellID]",
        "    }",
        "",
        "    static func entry(for family: FallbackScriptFamily, governanceReason: FallbackGovernanceReason) -> FallbackScriptCatalogEntry? {",
        "        entries.first { $0.family == family && governanceReasons[$0.cellID] == governanceReason }",
        "    }",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--json-output", type=Path, required=True)
    parser.add_argument("--swift-output", type=Path, required=True)
    args = parser.parse_args()

    source_bytes = args.source.read_bytes()
    source = json.loads(source_bytes)
    source_sha = hashlib.sha256(source_bytes).hexdigest()
    catalog = {
        "schemaVersion": "demo_fallback_script_catalog.v1",
        "sourceSHA256": source_sha,
        "entries": [public_entry(source, cell) for cell in source["cells"]],
    }
    args.json_output.parent.mkdir(parents=True, exist_ok=True)
    args.swift_output.parent.mkdir(parents=True, exist_ok=True)
    args.json_output.write_text(
        json.dumps(catalog, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    args.swift_output.write_text(generate_swift(source, source_sha), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
