#!/usr/bin/env python3
"""Generate deterministic fallback catalog views from source plus the T0 registry."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any


def swift_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def swift_case(value: str) -> str:
    pieces = value.replace("-", "_").split("_")
    return pieces[0] + "".join(piece[:1].upper() + piece[1:] for piece in pieces[1:])


def enum_source(name: str, values: list[str], visibility: str = "public", codable: bool = True) -> list[str]:
    protocols = "CaseIterable, Codable, Hashable, Sendable" if codable else "CaseIterable, Hashable, Sendable"
    lines = [f"{visibility} enum {name}: String, {protocols} {{"]
    lines.extend(f"    case {swift_case(value)} = {swift_string(value)}" for value in values)
    lines.append("}")
    return lines


def load_registry(source: dict[str, Any], repo_root: Path, override: Path | None) -> tuple[dict[str, Any], Path]:
    authority = source.get("authority", {})
    if not isinstance(authority, dict) or authority.get("t0_change") != "add-c1-demo-capability-governance":
        raise ValueError("fallback source must pin the add-c1-demo-capability-governance authority")
    registry_reference = authority.get("t0_registry")
    if override is None:
        if not isinstance(registry_reference, str):
            raise ValueError("fallback source must name t0_registry")
        path = (repo_root / registry_reference).resolve()
    else:
        path = override.resolve()
    registry = json.loads(path.read_text(encoding="utf-8"))
    if registry.get("change_id") != "add-c1-demo-capability-governance":
        raise ValueError("T0 registry change id mismatch")
    if not isinstance(registry.get("fallback_catalog_buckets"), list):
        raise ValueError("T0 registry lacks fallback catalog buckets")
    return registry, path


def public_cell_id(source: dict[str, Any], cell: dict[str, Any]) -> str:
    # Stable public identifier deliberately excludes governance vocabulary.
    index = source["cells"].index(cell) + 1
    return f"fallback.{cell['family']}.{index:02d}.{cell['locale']}"


def public_entry(source: dict[str, Any], cell: dict[str, Any]) -> dict[str, Any]:
    family = cell["family"]
    return {
        "cellID": public_cell_id(source, cell),
        "locale": cell["locale"],
        "family": family,
        "familyLabel": source["families"][family]["familyLabel"],
        "resultKind": cell["result_kind"],
        "safeReasonKind": cell["safeReasonKind"],
        "dialogText": cell["dialogText"],
        "ttsText": cell["ttsText"],
        "badgeLabel": cell["badgeLabel"],
    }


def generate_reason_authority_swift(registry: dict[str, Any], registry_sha: str) -> str:
    lines = [
        "// Generated by Tools/generate_fallback_script_catalog_swift.py. Do not edit.",
        "// Semantic source: openspec/changes/add-c1-demo-capability-governance/ownership-map.yaml",
        f"// T0 registry SHA-256: {registry_sha}",
        "",
    ]
    reason_enum = enum_source("RuntimePresentationSafeReasonKind", registry["reasonKind_enum"], "public")
    lines.extend(reason_enum[:-1])
    lines.extend(
        [
            "",
            "    public init?(finiteReason: String) {",
            "        guard let projection = RuntimePresentationReasonAuthority.projection(forFiniteReason: finiteReason) else {",
            "            return nil",
            "        }",
            "        self = projection.safeReasonKind",
            "    }",
            "}",
            "",
            "public struct RuntimePresentationReasonProjection: Equatable, Sendable {",
            "    public let safeReasonKind: RuntimePresentationSafeReasonKind",
            "    public let result: DemoRuntimeResult",
            "}",
            "",
            "public enum RuntimePresentationReasonAuthority {",
            "    public static let finiteReasons: [String] = [",
        ]
    )
    for finite_reason in registry["finiteReason_enum"]:
        lines.append(f"        {swift_string(finite_reason)},")
    lines.extend(
        [
            "    ]",
            "",
            "    private static let projections: [String: RuntimePresentationReasonProjection] = [",
        ]
    )
    for projection in registry["finiteReason_projections"]:
        lines.extend(
            [
                f"        {swift_string(projection['finiteReason'])}: RuntimePresentationReasonProjection(",
                f"            safeReasonKind: .{swift_case(projection['reasonKind'])},",
                f"            result: .{swift_case(projection['bridge_result'])}",
                "        ),",
            ]
        )
    lines.extend(
        [
            "    ]",
            "",
            "    public static func projection(forFiniteReason finiteReason: String) -> RuntimePresentationReasonProjection? {",
            "        projections[finiteReason]",
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def generate_swift(source: dict[str, Any], source_sha: str, registry: dict[str, Any], registry_sha: str) -> str:
    governance_reasons = [item["reason_kind"] for item in registry["fallback_catalog_buckets"]]
    lines = [
        "// Generated by Tools/generate_fallback_script_catalog_swift.py. Do not edit.",
        f"// Source SHA-256: {source_sha}",
        f"// T0 registry SHA-256: {registry_sha}",
        "",
    ]
    lines.extend(enum_source("FallbackScriptFamily", source["family_enum"], "public"))
    lines.append("")
    lines.extend(enum_source("FallbackGovernanceReason", governance_reasons, "internal", False))
    lines.extend(
        [
            "",
            "public typealias FallbackSafeReasonKind = RuntimePresentationSafeReasonKind",
            "public typealias FallbackResultKind = DemoRuntimeResult",
            "",
            "public struct FallbackScriptCatalogEntry: Codable, Equatable, Hashable, Sendable {",
            "    public let cellID: String",
            "    public let locale: String",
            "    public let family: FallbackScriptFamily",
            "    public let familyLabel: String",
            "    public let resultKind: DemoRuntimeResult",
            "    public let safeReasonKind: RuntimePresentationSafeReasonKind",
            "    public let dialogText: String",
            "    public let ttsText: String",
            "    public let badgeLabel: String",
            "}",
            "",
            "public enum FallbackScriptCatalog {",
            f"    public static let sourceSHA256 = {swift_string(source_sha)}",
            "    private static let familyAliases: [String: FallbackScriptFamily] = [",
        ]
    )
    aliases: list[tuple[str, str]] = []
    for family in source["family_enum"]:
        aliases.append((family, family))
        aliases.extend((alias, family) for alias in source["families"][family].get("aliases", []))
    for alias, family in sorted(aliases):
        lines.append(f"        {swift_string(alias)}: .{swift_case(family)},")
    lines.extend(
        [
            "    ]",
            "",
            "    public static func normalizeFamily(_ rawValue: String) -> FallbackScriptFamily? {",
            "        familyAliases[rawValue]",
            "    }",
            "",
            "    public static let entries: [FallbackScriptCatalogEntry] = [",
        ]
    )
    for cell in source["cells"]:
        family = cell["family"]
        lines.extend(
            [
                "        FallbackScriptCatalogEntry(",
                f"            cellID: {swift_string(public_cell_id(source, cell))},",
                f"            locale: {swift_string(cell['locale'])},",
                f"            family: .{swift_case(family)},",
                f"            familyLabel: {swift_string(source['families'][family]['familyLabel'])},",
                f"            resultKind: .{swift_case(cell['result_kind'])},",
                f"            safeReasonKind: .{swift_case(cell['safeReasonKind'])},",
                f"            dialogText: {swift_string(cell['dialogText'])},",
                f"            ttsText: {swift_string(cell['ttsText'])},",
                f"            badgeLabel: {swift_string(cell['badgeLabel'])}",
                "        ),",
            ]
        )
    lines.extend(["    ]", "", "    private static let governanceReasons: [String: FallbackGovernanceReason] = ["])
    for cell in source["cells"]:
        lines.append(f"        {swift_string(public_cell_id(source, cell))}: .{swift_case(cell['reason_kind'])},")
    lines.extend(
        [
            "    ]",
            "",
            "    /// Internal lookup for Core consumers; governance reason never enters the Codable entry.",
            "    static func governanceReason(for entry: FallbackScriptCatalogEntry) -> FallbackGovernanceReason? {",
            "        governanceReasons[entry.cellID]",
            "    }",
            "",
            "    static func entry(for family: FallbackScriptFamily, governanceReason: FallbackGovernanceReason) -> FallbackScriptCatalogEntry? {",
            "        entries.first { $0.family == family && governanceReasons[$0.cellID] == governanceReason }",
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--json-output", type=Path, required=True)
    parser.add_argument("--swift-output", type=Path, required=True)
    parser.add_argument("--reason-authority-output", type=Path, required=True)
    parser.add_argument("--t0-registry", type=Path)
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    source_bytes = args.source.read_bytes()
    source = json.loads(source_bytes)
    registry, registry_path = load_registry(source, repo_root, args.t0_registry)
    source_sha = hashlib.sha256(source_bytes).hexdigest()
    registry_sha = hashlib.sha256(registry_path.read_bytes()).hexdigest()
    catalog = {
        "schemaVersion": "demo_fallback_script_catalog.v1",
        "sourceSHA256": source_sha,
        "t0RegistrySHA256": registry_sha,
        "entries": [public_entry(source, cell) for cell in source["cells"]],
    }
    args.json_output.parent.mkdir(parents=True, exist_ok=True)
    args.swift_output.parent.mkdir(parents=True, exist_ok=True)
    args.reason_authority_output.parent.mkdir(parents=True, exist_ok=True)
    args.json_output.write_text(
        json.dumps(catalog, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    args.swift_output.write_text(generate_swift(source, source_sha, registry, registry_sha), encoding="utf-8")
    args.reason_authority_output.write_text(
        generate_reason_authority_swift(registry, registry_sha),
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
