#!/usr/bin/env python3
"""Deterministically select canonical semantic rows and emit runtime artifacts."""
from __future__ import annotations
import argparse, hashlib, json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

class SelectionError(ValueError): pass

@dataclass(frozen=True)
class SemanticSelection:
    contract_row_id: str
    source_row_hash: str
    canonical_semantic_id: str
    runtime_use: str

def select_semantic_rows(rows: list[dict[str, Any]], selections: list[SemanticSelection]) -> list[dict[str, Any]]:
    by_key = {(r.get('contract_row_id'), r.get('source_row_hash'), r.get('canonical_semantic_id')): r for r in rows}
    if len(by_key) != len(rows): raise SelectionError('duplicate canonical row identity')
    used: set[str] = set(); out = []
    for s in selections:
        if s.runtime_use in used: raise SelectionError('duplicate runtimeUse')
        used.add(s.runtime_use)
        key = (s.contract_row_id, s.source_row_hash, s.canonical_semantic_id)
        row = by_key.get(key)
        if row is None: raise SelectionError('E_RUNTIME_BUNDLE_SELECTION_NOT_FOUND:' + s.contract_row_id)
        out.append(row)
    return out

def canonical_bytes(value: Any) -> bytes:
    return (json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(',', ':')) + '\n').encode()

def _load(path: Path) -> bytes: return path.read_bytes()
def _sha(data: bytes) -> str: return hashlib.sha256(data).hexdigest()

def generate(root: Path) -> tuple[dict[str, Any], str]:
    selection_path = root/'contracts/demo-runtime-bundle-selection.json'
    selection = json.loads(_load(selection_path))
    rows = [json.loads(line) for line in _load(root/'contracts/semantic-function-contract.jsonl').decode().splitlines() if line.strip()]
    sels = [SemanticSelection(x['contractRowID'], x['sourceRowHash'], x['canonicalSemanticID'], x['runtimeUse']) for x in selection['semanticRows']]
    selected = select_semantic_rows(rows, sels)
    projected = b''.join(canonical_bytes(r) for r in selected)
    schema = _load(root/'contracts/schemas/demo-runtime-bundle-selection.schema.json')
    digest_input = {'schemaVersion':'demo_runtime_bundle_digest_v1','generatorContract':'demo_runtime_contract_bundle_generator_v1','generatorSHA256':_sha(_load(Path(__file__))),'selectionManifestSHA256':_sha(_load(selection_path)),'selectionSchemaSHA256':_sha(schema),'sourceSHA256':{'semantic':_sha(_load(root/'contracts/semantic-function-contract.jsonl'))},'projectionSHA256':{'semantic':_sha(projected)}}
    digest = _sha(canonical_bytes(digest_input))
    manifest = {'schema_version':'demo_runtime_contract_bundle_manifest_v1','catalog_schema_version':'demo_runtime_contract_bundle_v1','runtime_contract_bundle_digest':digest,'selection_manifest_sha256':digest_input['selectionManifestSHA256'],'selection_schema_sha256':digest_input['selectionSchemaSHA256'],'generator_contract':'demo_runtime_contract_bundle_generator_v1','selected_semantic_rows':selected,'digest_input':digest_input}
    return manifest, digest

def swift_block(value: str) -> str:
    return value.replace('\\', '\\\\').replace('"""', '\\"\\"\\"')

def main() -> int:
    p=argparse.ArgumentParser(); p.add_argument('--root', default=Path(__file__).resolve().parents[1]); args=p.parse_args(); root=Path(args.root)
    manifest,digest=generate(root); out=root/'generated/demo-runtime-contract-bundle.manifest.json'; out.parent.mkdir(exist_ok=True); out.write_bytes(canonical_bytes(manifest))
    swift=root/'Core/Contracts/DemoRuntimeContractBundle.generated.swift'
    semantic='\n'.join(json.dumps(row, ensure_ascii=False, separators=(',', ':')) for row in manifest['selected_semantic_rows'])+'\n'
    state=(root/'contracts/state-cells.yaml').read_text(encoding='utf-8')
    risk=(root/'contracts/risk-policy.yaml').read_text(encoding='utf-8')
    allowlist=(root/'contracts/l1-demo-allowlist.yaml').read_text(encoding='utf-8')
    swift.write_text('// Generated by Tools/generate_demo_runtime_contract_bundle.py. Do not edit.\nimport Foundation\n\npublic enum DemoRuntimeContractBundleCatalog {\n    public static let schemaVersion = "demo_runtime_contract_bundle_v1"\n    public static let runtimeContractBundleDigest = "'+digest+'"\n    public static let generatedDefault = DemoRuntimeContractBundle(\n        semanticJSONL: """\n'+swift_block(semantic)+'""",\n        stateCellsYAML: """\n'+swift_block(state)+'\n""",\n        riskPolicyYAML: """\n'+swift_block(risk)+'\n""",\n        allowlistYAML: """\n'+swift_block(allowlist)+'\n"""\n    )\n}\n')
    return 0
if __name__ == '__main__': raise SystemExit(main())
